### ISSUE TITLE
cap2musicxml.exe release

### ISSUE THREAD

**Issue by samarutuk** [lg2de/cap2musicxml#1]
Could you provide a ready-made _cap2musicxml.exe_ under **Releases** for all people who can't compile themselves? That would be really great, because I'm one of those people who still have a lot of older cap files and would like to convert them.

Thanks in advance
Sam

**Comment by lg2de** [comment]
I'm wondering why I did not get notification for your request.
Accidentally today I browsed through my repos and found this one in an quite old state. So, I decided to update to latest .NET Framework version. Further I found a fork which added an artifact, so I added this now.
THEN I noticed this (first!) issue which is now resolved.
Thanks for your request and patience. Hope it is useful!
